name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
#Test update
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Terraform variables from secrets
      run: |
      echo "subscription_id = \"$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')\"" > terraform.tfvars
      echo "client_id = \"$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')\"" >> terraform.tfvars
      echo "client_secret = \"$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')\"" >> terraform.tfvars
      echo "tenant_id = \"$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.tenantId')\"" >> terraform.tfvars

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
