name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Terraform variables from secrets
      run: |
        echo "subscription_id = \"$(jq -r '.subscriptionId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" > terraform.tfvars
        echo "client_id = \"$(jq -r '.clientId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> terraform.tfvars
        echo "client_secret = \"$(jq -r '.clientSecret' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> terraform.tfvars
        echo "tenant_id = \"$(jq -r '.tenantId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> terraform.tfvars

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
